{
  "openapi": "3.0.3",
  "info": {
    "title": "Boarding House  OpenAPI",
    "description": "API Specification for Boarding House",
    "version": "1.0.0",
    "contact": {
      "name": "Didi Prasetyo",
      "email": "didiprasetyo360@gmail.com",
      "url": "https://prasetyodidi.github.io/"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/room/{roomId}/rules": {
      "get": {
        "parameters": [
          {
            "$ref": "#/components/parameters/roomId"
          }
        ],
        "description": "get all rules",
        "responses": {
          "200": {
            "$ref": "#/components/responses/rulesSuccessResponse"
          },
          "404": {
            "$ref": "#/components/responses/boardingHouseIdNotFoundResponse"
          }
        }
      }
    },
    "/room/{roomId}/reminder": {
      "get": {
        "parameters": [
          {
            "$ref": "#/components/parameters/roomId"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/reminderSuccessResponse"
          },
          "404": {
            "$ref": "#/components/responses/boardingHouseIdNotFoundResponse"
          }
        }
      }
    },
    "/room/{roomId}/info": {
      "description": "get detail room info",
      "get": {
        "parameters": [
          {
            "$ref": "#/components/parameters/roomId"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/detailRoomSuccessResponse"
          },
          "404": {
            "$ref": "#/components/responses/roomIdNotFoundResponse"
          }
        }
      }
    },
    "/room/{roomId}/reminder-date-range": {
      "description": "date reminder",
      "get": {
        "parameters": [
          {
            "$ref": "#/components/parameters/roomId"
          }
        ],
        "responses": {
          "200": {
            "description": "success get date reminder",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "start_date": {
                          "type": "integer",
                          "format": "int64"
                        },
                        "end_date": {
                          "type": "integer",
                          "format": "int64"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "success get date reminder",
                    "value": {
                      "status": "success",
                      "message": "success get date reminder",
                      "data": {
                        "start_date": 1657317715,
                        "end_date": 1659043363
                      }
                    }
                  },
                  "fail": {
                    "description": "success get date reminder",
                    "value": {
                      "status": "fail",
                      "message": "room id invalid",
                      "data": {
                        "date_reminder": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/roomIdNotFoundResponse"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "boardingHouseId": {
        "name": "boardingHouseId",
        "description": "boarding house id",
        "in": "path"
      },
      "roomId": {
        "name": "roomId",
        "description": "room id",
        "in": "path"
      },
      "ownerIdQuery": {
        "in": "query",
        "description": "selection boarding house by owner id",
        "name": "ownerId",
        "schema": {
          "minLength": 1,
          "type": "string",
          "required": false
        }
      },
      "tenantIdQuery": {
        "in": "query",
        "description": "selection boarding house by tenant id",
        "name": "tenantId",
        "schema": {
          "minLength": 1,
          "type": "string",
          "required": false
        }
      }
    },
    "responses": {
      "rulesSuccessResponse": {
        "description": "response get rules",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "required": true
                },
                "message": {
                  "type": "string",
                  "required": true
                },
                "data": {
                  "$ref": "#/components/schemas/rule"
                }
              }
            },
            "examples": {
              "Kos Putra 1": {
                "description": "success get rules",
                "value": {
                  "status": "success",
                  "message": "success get rules",
                  "data": {
                    "boarding_house_name": "Kos Putra 1",
                    "rules": [
                      "rules one",
                      "rules two",
                      "rules three",
                      "rules four",
                      "rules five"
                    ]
                  }
                }
              },
              "Kos Putri 1": {
                "description": "success get rules",
                "value": {
                  "status": "success",
                  "message": "success get rules",
                  "data": {
                    "boarding_house_name": "Kos Putri 1",
                    "rules": [
                      "rules one",
                      "rules two",
                      "rules three",
                      "rules four",
                      "rules five"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "reminderSuccessResponse": {
        "description": "response get reminder",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "required": true
                },
                "message": {
                  "type": "string",
                  "required": true
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "date_reminder": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "reminders": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/reminder"
                      }
                    }
                  }
                }
              }
            },
            "examples": {
              "Kos Putra 1": {
                "description": "success get reminder",
                "value": {
                  "status": "success",
                  "message": "success get reminder",
                  "data": {
                    "date_reminder": 23,
                    "reminders": [
                      {
                        "reminder": "buang sampah",
                        "image_url": "www.example.com/imageOne"
                      },
                      {
                        "reminder": "bersih bersih",
                        "image_url": "www.example.com/imageTwo"
                      },
                      {
                        "reminder": "iuran kebersihan",
                        "image_url": "www.example.com/imageThree"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "boardingHouseSuccessResponse": {
        "description": "success get list boarding house",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "address": {
                        "type": "string"
                      },
                      "image_url": {
                        "type": "string"
                      }
                    }
                  }
                }
              },
              "required": [
                "status",
                "message",
                "data"
              ]
            }
          }
        }
      },
      "boardingHouseIdNotFoundResponse": {
        "description": "boarding house id not found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Room id invalid": {
                "description": "failed get rules",
                "value": {
                  "status": "fail",
                  "message": "room id invalid"
                }
              }
            }
          }
        }
      },
      "roomIdNotFoundResponse": {
        "description": "Room id not found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Room id invalid": {
                "description": "failed get reminder",
                "value": {
                  "status": "fail",
                  "message": "Room id invalid"
                }
              }
            }
          }
        }
      },
      "detailRoomSuccessResponse": {
        "description": "Success get detail room info",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "required": true
                },
                "message": {
                  "type": "string",
                  "required": true
                },
                "data": {
                  "$ref": "#/components/schemas/roomInfo"
                }
              }
            }
          }
        }
      }
    },
    "schemas": {
      "rule": {
        "type": "object",
        "properties": {
          "boarding_house_name": {
            "type": "string"
          },
          "rules": {
            "type": "array",
            "required": true,
            "items": {
              "type": "string"
            }
          }
        }
      },
      "reminder": {
        "type": "object",
        "properties": {
          "reminder": {
            "type": "string"
          },
          "image_url": {
            "type": "string"
          }
        }
      },
      "roomInfo": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "boarding_house_name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          },
          "owner_name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          },
          "address": {
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          },
          "image_url": {
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          }
        }
      }
    }
  }
}
